[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.17"

[profile.default.fmt]
line_length = 100
tab_width = 4
bracket_spacing = false

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
